module.exports = function ( sourceModel ) {
   var customFilterColumnPath = sourceModel.type == "Region" ? "Code" : "Name";

   const payload = `{
    "rootSchemaName": "${sourceModel.type}",
    "operationType":0,
    "includeProcessExecutionData":true,
    "filters":{
       "items":{
          "56466c04-525c-41c8-92d9-abedfffc8f35":{
             "items":{
                "CustomFilters":{
                   "items":{
                      "customFilterName_${sourceModel.type}":{
                         "filterType":1,
                         "comparisonType":3,
                         "isEnabled":true,
                         "trimDateTimeParameterToDate":false,
                         "leftExpression":{
                            "expressionType":0,
                            "columnPath":"${customFilterColumnPath}"
                         },
                         "rightExpression":{
                            "expressionType":2,
                            "parameter":{
                               "dataValueType":1,
                               "value": "${sourceModel.value}"
                            }
                         }
                      }
                   },
                   "logicalOperation":0,
                   "isEnabled":true,
                   "filterType":6
                }
             },
             "logicalOperation":0,
             "isEnabled":true,
             "filterType":6
          }
       },
       "logicalOperation":0,
       "isEnabled":true,
       "filterType":6
    },
    "columns":{
       "items":{
          "Id":{
             "caption":"",
             "orderDirection":0,
             "orderPosition":-1,
             "isVisible":true,
             "expression":{
                "expressionType":0,
                "columnPath":"Id"
             }
          },
          "Name":{
             "caption":"",
             "orderDirection":0,
             "orderPosition":-1,
             "isVisible":true,
             "expression":{
                "expressionType":0,
                "columnPath":"Name"
             }
          },
          "EntryPointsCount":{
             "caption":"",
             "orderDirection":0,
             "orderPosition":-1,
             "isVisible":true,
             "expression":{
                "expressionType":3,
                "aggregationType":1,
                "columnPath":"[EntryPoint:EntityId].Id",
                "subFilters":{
                   "items":{
                      "5aedb39e-6d4d-4e36-bda4-d70442b820bc":{
                         "filterType":1,
                         "comparisonType":3,
                         "isEnabled":true,
                         "trimDateTimeParameterToDate":false,
                         "leftExpression":{
                            "expressionType":0,
                            "columnPath":"IsActive"
                         },
                         "rightExpression":{
                            "expressionType":2,
                            "parameter":{
                               "dataValueType":1,
                               "value":true
                            }
                         }
                      }
                   },
                   "logicalOperation":0,
                   "isEnabled":true,
                   "filterType":6
                }
             }
          },
          "Description":{
             "caption":"",
             "orderDirection":0,
             "orderPosition":-1,
             "isVisible":true,
             "expression":{
                "expressionType":0,
                "columnPath":"Description"
             }
          },
          "ProcessListeners":{
             "caption":"",
             "orderDirection":0,
             "orderPosition":-1,
             "isVisible":true,
             "expression":{
                "expressionType":0,
                "columnPath":"ProcessListeners"
             }
          }
       }
    },
    "isDistinct":false,
    "rowCount":30,
    "rowsOffset":0,
    "isPageable":true,
    "allColumns":false,
    "useLocalization":true,
    "useRecordDeactivation":false,
    "serverESQCacheParameters":{
       "cacheLevel":0,
       "cacheGroup":"",
       "cacheItemName":""
    },
    "queryOptimize":false,
    "useMetrics":false,
    "adminUnitRoleSources":0,
    "querySource":0,
    "ignoreDisplayValues":false,
    "conditionalValues":"None",
    "isHierarchical":false
   }`;

  return JSON.parse(payload);
};
